version: '3'
services:
  redis-server:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
  tik-tak-toe-app:
    build:
      context: ../
      dockerfile: containers/Dockerfile
    links:
      - redis-server
    ports:
      - "9099:9099"